// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCtmSSNIxw3-dnJzF64bpECJsSL-rkWnuc',
    appId: '1:1026587875507:android:359d75b8ec7fb84a47f8c6',
    messagingSenderId: '1026587875507',
    projectId: 'test2-4446b',
    storageBucket: 'test2-4446b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD6R5ODBAIpHGjG8urMbJ58tOyBI0-dmFw',
    appId: '1:1026587875507:ios:55c63c52af5a6cd647f8c6',
    messagingSenderId: '1026587875507',
    projectId: 'test2-4446b',
    storageBucket: 'test2-4446b.firebasestorage.app',
    iosBundleId: 'com.example.test2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD6R5ODBAIpHGjG8urMbJ58tOyBI0-dmFw',
    appId: '1:1026587875507:ios:55c63c52af5a6cd647f8c6',
    messagingSenderId: '1026587875507',
    projectId: 'test2-4446b',
    storageBucket: 'test2-4446b.firebasestorage.app',
    iosBundleId: 'com.example.test2',
  );
}
